<?php

namespace Reliefapps\NotificationBundle\Repository;

/**
 * UserDeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserDeviceRepository extends \Doctrine\ORM\EntityRepository
{
}
